//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace guRoo.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("guRoo.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user will generally not see this - it just holds the PushButton example..
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of adding a PushButton to a RibbonPanel..
        /// </summary>
        internal static string Button_Button {
            get {
                return ResourceManager.GetString("Button_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of adding a PulldownButton to a RibbonPanel..
        /// </summary>
        internal static string PullDown {
            get {
                return ResourceManager.GetString("PullDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is button 1 of the PulldownButton..
        /// </summary>
        internal static string PullDown_1Button {
            get {
                return ResourceManager.GetString("PullDown_1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is button 2 of the PulldownButton..
        /// </summary>
        internal static string PullDown_2Button {
            get {
                return ResourceManager.GetString("PullDown_2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is button 3 of the PulldownButton..
        /// </summary>
        internal static string PullDown_3Button {
            get {
                return ResourceManager.GetString("PullDown_3Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands relating to revisions..
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected revision to selected sheets..
        /// </summary>
        internal static string Revision_BulkRev {
            get {
                return ResourceManager.GetString("Revision_BulkRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools related to selection..
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all title blocks on selected sheets..
        /// </summary>
        internal static string Select_GetTtbs {
            get {
                return ResourceManager.GetString("Select_GetTtbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a filtered selection for hidden elements..
        /// </summary>
        internal static string Select_PickHidden {
            get {
                return ResourceManager.GetString("Select_PickHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a filtered selection for rooms..
        /// </summary>
        internal static string Select_PickRooms {
            get {
                return ResourceManager.GetString("Select_PickRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack1 {
            get {
                return ResourceManager.GetString("Stack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack1_Button {
            get {
                return ResourceManager.GetString("Stack1_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack2 {
            get {
                return ResourceManager.GetString("Stack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack2_Button {
            get {
                return ResourceManager.GetString("Stack2_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack3 {
            get {
                return ResourceManager.GetString("Stack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of stacking buttons..
        /// </summary>
        internal static string Stack3_Button {
            get {
                return ResourceManager.GetString("Stack3_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools related to worksets..
        /// </summary>
        internal static string Workset {
            get {
                return ResourceManager.GetString("Workset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create worksets from a list of common names..
        /// </summary>
        internal static string Workset_Create {
            get {
                return ResourceManager.GetString("Workset_Create", resourceCulture);
            }
        }
    }
}
